const texts = [
  "The quick brown fox jumps over the lazy dog.",
  "In the beginning, God created the heavens and the earth.",
  "All that glitters is not gold.",
  "To be or not to be, that is the question.",
  "A journey of a thousand miles begins with a single step.",
  "The only thing we have to fear is fear itself.",
  "Two roads diverged in a wood, and I took the one less traveled by.",
  "It was the best of times, it was the worst of times.",
  "To err is human; to forgive, divine.",
  "The more you know, the more you realize you don't know.",
  "Life is what happens when you're busy making other plans.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Believe you can and you're halfway there.",
  "The purpose of our lives is to be happy.",
  "Change your thoughts and you change your world.",
  "To live is the rarest thing in the world. Most people exist, that is all.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "You miss 100% of the shots you don't take.",
  "Be the change that you wish to see in the world.",
  "The only way to do great work is to love what you do.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "The mind is everything. What you think you become.",
  "It always seems impossible until it's done.",
  "Success is stumbling from failure to failure with no loss of enthusiasm.",
  "To love and be loved is to feel the sun from both sides.",
  "You are never too old to set another goal or to dream a new dream.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Believe you can and you're halfway there.",
  "The purpose of our lives is to be happy.",
  "Change your thoughts and you change your world.",
  "To live is the rarest thing in the world. Most people exist, that is all.",
  "Life is what happens when you're busy making other plans.",
  "The only constant in life is change.",
  "Where there is love, there is life.",
  "Don't cry because it's over, smile because it happened.",
  "Life is either a daring adventure or nothing at all.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Strive not to be a success, but rather to be of value.",
  "The best revenge is massive success.",
  "Your time is limited, don't waste it living someone else's life.",
  "If you want to achieve greatness, stop asking for permission.",
  "The only way to do great work is to love what you do.",
  "It's not whether you get knocked down, it's whether you get up.",
  "Your attitude, not your aptitude, will determine your altitude.",
  "The greatest pleasure in life is doing what people say you cannot do.",
  "The best way to predict the future is to create it.",
  "Life is really simple, but we insist on making it complicated.",
  "I find that the harder I work, the more luck I seem to have.",
  "The only place where success comes before work is in the dictionary.",
  "It's not what you look at that matters, it's what you see.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Life is short, and it's up to you to make it sweet.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The way to get started is to quit talking and begin doing.",
  "Life is what happens when you're busy making other plans.",
  "You miss 100% of the shots you don't take.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "You are never too old to set another goal or to dream a new dream.",
  "It always seems impossible until it's done.",
  "The mind is everything. What you think you become.",
  "Believe you can and you're halfway there.",
  "To live is the rarest thing in the world. Most people exist, that is all.",
  "The only way to do great work is to love what you do.",
  "Your time is limited, don't waste it living someone else's life.",
  "I find that the harder I work, the more luck I seem to have.",
  "Life is either a daring adventure or nothing at all.",
  "Strive not to be a success, but rather to be of value.",
  "Don't cry because it's over, smile because it happened.",
  "If you want to achieve greatness, stop asking for permission.",
  "Your attitude, not your aptitude, will determine your altitude.",
  "The best way to predict the future is to create it.",
  "The best revenge is massive success.",
  "It's not whether you get knocked down, it's whether you get up.",
  "The only place where success comes before work is in the dictionary.",
  "It's not what you look at that matters, it's what you see.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Life is short, and it's up to you to make it sweet.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Life is really simple, but we insist on making it complicated.",
  "The greatest pleasure in life is doing what people say you cannot do.",
  "In the end, we will remember not the words of our enemies, but the silence of our friends.",
  "The only thing we have to fear is fear itself.",
  "In the beginning, God created the heavens and the earth.",
  "A journey of a thousand miles begins with a single step.",
  "To err is human; to forgive, divine.",
  "Change your thoughts and you change your world.",
  "The purpose of our lives is to be happy.",
  "Two roads diverged in a wood, and I took the one less traveled by.",
  "The only constant in life is change.",
  "Where there is love, there is life.",
  "The best preparation for tomorrow is doing your best today.",
  "The mind is everything. What you think you become.",
  "Life is what happens when you're busy making other plans.",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
  "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.",
  "I hear and I forget. I see and I remember. I do and I understand.",
  "It does not matter how slowly you go as long as you do not stop.",
  "If you can dream it, you can do it.",
  "Success is not in what you have, but who you are.",
  "To accomplish great things, we must not only act but also dream; not only plan but also believe.",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.",
  "The only place where success comes before work is in the dictionary.",
  "It always seems impossible until it's done.",
  "The best way to predict the future is to create it.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "You are never too old to set another goal or to dream a new dream.",
  "Believe you can and you're halfway there.",
  "To live is the rarest thing in the world. Most people exist, that is all.",
  "It's not whether you get knocked down, it's whether you get up.",
  "Your time is limited, don't waste it living someone else's life.",
  "The only constant in life is change.",
  "Where there is love, there is life.",
  "Don't cry because it's over, smile because it happened.",
  "Life is either a daring adventure or nothing at all.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Strive not to be a success, but rather to be of value.",
  "The best revenge is massive success.",
  "Your attitude, not your aptitude, will determine your altitude.",
  "The greatest pleasure in life is doing what people say you cannot do.",
  "The best way to predict the future is to create it.",
  "Life is really simple, but we insist on making it complicated.",
  "I find that the harder I work, the more luck I seem to have.",
  "In the end, we will remember not the words of our enemies, but the silence of our friends.",
  "The only thing we have to fear is fear itself.",
  "In the beginning, God created the heavens and the earth.",
  "A journey of a thousand miles begins with a single step.",
  "To err is human; to forgive, divine.",
  "Change your thoughts and you change your world.",
  "The purpose of our lives is to be happy.",
  "Two roads diverged in a wood, and I took the one less traveled by.",
  "The only constant in life is change.",
  "Where there is love, there is life.",
  "The best preparation for tomorrow is doing your best today.",
  "The mind is everything. What you think you become.",
  "Life is what happens when you're busy making other plans.",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
  "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.",
  "I hear and I forget. I see and I remember. I do and I understand.",
  "It does not matter how slowly you go as long as you do not stop.",
  "If you can dream it, you can do it.",
  "Success is not in what you have, but who you are.",
  "To accomplish great things, we must not only act but also dream; not only plan but also believe.",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.",
];
export default texts;
